# Generated by Django 2.1.4 on 2018-12-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0002_auto_20181206_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='attributes',
        ),
        migrations.AddField(
            model_name='sku',
            name='attrs',
            field=models.ManyToManyField(db_table='attrs2skus', related_name='sku', related_query_name='skus', to='sku.Attribute'),
        ),
        migrations.AddField(
            model_name='sku',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
