# Generated by Django 2.1.4 on 2018-12-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0003_auto_20181206_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='attrs',
            field=models.ManyToManyField(db_table='attrs2categories', related_name='categories', related_query_name='categories', to='sku.Attribute'),
        ),
    ]
