language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
    dist: xenial
    sudo: yes

env:
  - DJANGO_VERSION=2.1

install:
  - pip install -r requirements.pip
  - python3 manage.py migrate  

script:
  - python3 manage.py test