dist: xenial
language: python
cache: pip

python:
  - "3.5"
  - "3.6"
  - "3.7"

env:
  - DJANGO_VERSION=2.1

install:
  - pip install -r requirements.pip
  - python manage.py migrate

script:
  - python manage.py test
