# Generated by Django 2.1.4 on 2018-12-06 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SKUAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('valor', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SKUCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='skuattribute',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sku.SKUCategory'),
        ),
        migrations.AddField(
            model_name='sku',
            name='parameters',
            field=models.ManyToManyField(db_table='sku2attributes', related_name='attribute', related_query_name='attributes', to='sku.SKUAttribute'),
        ),
    ]
